name: publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cki build
        run: |
          version=0.2.0
          wget "https://github.com/keiki24/cki/releases/download/v${version}/cki_v${version}_x86_64-unknown-linux-musl.zip"
          unzip "cki_v${version}_x86_64-unknown-linux-musl.zip"
          ./cki build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output